spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/inventory
    username: ${DB_USER:testuser}
    password: ${DB_PASSWORD:testuser}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect