server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
  servlet:
    encoding:
      enabled: true
      force: true
      charset: "UTF-8"

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
    info.enabled: true

spring:
  application.name: inventory-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

firebase:
  service-account: firebase/admin-service-account.json
  project-id: falzone-web

application:
  allowedClients:
    postman:
      clientUsername: 123456
      clientPassword: password