name: Build Test and Deploy

on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set execution bit for mvnw
        run: chmod +x ./mvnw
      - name: Build
        run: ./mvnw -B package -DskipTests --file pom.xml
      - name: Run Unit Tests
        run: ./mvnw test
      - name: Run Integration Tests
        run: |
          ./mvnw verify

  release-snapshot:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Publish package
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-main:
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Release package
        run: |
          chmod +x ./mvnw
          ./mvnw --batch-mode release:prepare release:perform -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
